# Generated by Django 4.2.28 on 2026-03-24 12:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhs_number', models.CharField(help_text='10 digits. Spaces allowed.', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Enter NHS number as 10 digits, e.g. 123 456 7890.', regex='^\\d{3}\\s?\\d{3}\\s?\\d{4}$')])),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('height_m', models.DecimalField(decimal_places=2, help_text='Height in metres, e.g. 1.75', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.50')), django.core.validators.MaxValueValidator(Decimal('2.50'))])),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Weight in kilograms, e.g. 72.40', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('10.00')), django.core.validators.MaxValueValidator(Decimal('500.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
