# Generated by Django 4.2.28 on 2026-03-25 11:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic', models.PositiveIntegerField(help_text='Top number (mmHg). Normal is around 120.', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('diastolic', models.PositiveIntegerField(help_text='Bottom number (mmHg). Normal is around 80.', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(200)])),
                ('pulse', models.PositiveIntegerField(blank=True, help_text='Heart rate in beats per minute.', null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(250)])),
                ('arm', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], help_text='Which arm was the reading taken on?', max_length=5)),
                ('position', models.CharField(choices=[('sitting', 'Sitting'), ('standing', 'Standing'), ('prone', 'Prone')], default='sitting', help_text='Body position during reading.', max_length=8)),
                ('reading_date', models.DateField(help_text='Date the reading was taken.')),
                ('reading_time', models.TimeField(help_text='Time the reading was taken.')),
                ('comment', models.TextField(blank=True, default='', help_text='Optional notes about this reading.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reading_date', '-reading_time'],
            },
        ),
    ]
